apiVersion: v1
kind: Pod
metadata:
  name: nginx-limits-y-requests
spec:
  containers:
  - name: web
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"

