kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: developers
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["list","get","watch"]
- apiGroups: ["extensions","apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
