apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: landingpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx
        image: nginx:latest
