
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx2
  labels:
    project: nginx
spec:
  replicas: 2
  selector:
    project: nginx2
  template:
    metadata:
      name: nginx
      labels:
        project: nginx2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
