apiVersion: v1
kind: Pod
metadata:
  name: pod-all
  labels:
    service: nginx
spec:
  containers:
  - name: liveness
    image: nginx:latest
    readinessProbe:
      httpGet:
        path: /
        port: 80
        httpHeaders:
        - name: User-Agent
          value: "readiness-probe"
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: 80
        httpHeaders:
        - name: User-Agent
          value: "liveness-probe"            
      periodSeconds: 5

    startupProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 5
